<form action='/users' method='post'>
<div>
    <label>
        Имя
        <input type='text' name='user[name]' value ='<?= htmlspecialchars($user['name'])?>'>
    </label>
</div>
<?php if(!empty($errors['name'])): ?>
    <?= $errors['name']?>
<?php endif ?>
<div>
    <label>
        Email
        <input type='email' required name='user[email]' value='<?= htmlspecialchars($user['email'])?>'>
    </label>
</div>
<?php if(!empty($errors['email'])): ?>
    <?= $errors['email']?>
<?php endif ?>
<div>
    <label>
        <input type='submit' value='Создать'>
    </label>
</div>
</form>